=== jimenezperezpablo/Apuntes/Apuntes/Apuntes_LenguajeDeMarcas/Ejercicios/Ejercicio_Relacion4/Ejercicio2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="categoria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Periferico" />
                                        <xs:enumeration value="Ordenador" />
                                        <xs:enumeration value="Movil" />
                                        <xs:enumeration value="Accesorio" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:pattern value="\d+\.\d{2}"></xs:pattern>
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="stock">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:maxInclusive value="1000"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>


                            <xs:element name="proveedor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="telefono">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{3}-\d{3}-\d{3}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="pais" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>


                        </xs:sequence>


                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger"></xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>


                </xs:element>


            </xs:sequence>
        </xs:complexType>


    </xs:element>


</xs:schema>

=== jimenezperezpablo/Apuntes/Apuntes/Apuntes_LenguajeDeMarcas/Ejercicios/Ejercicio_Relacion4/Ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio2.xsd">


    <producto id="15">
        <nombre></nombre>
        <categoria>Periferico</categoria>
        <precio>89.99</precio>
        <stock>15</stock>
        <proveedor>
            <nombre></nombre>
            <telefono>698-214-456</telefono>
            <pais></pais>
        </proveedor>
    </producto>
</inventario>
